#!/bin/bash

SCRIPT_DIR=`dirname $0`

SUBFOLDERS=(server/external/libzmq git@github.com:zeromq/libzmq.git master)

UpdateNestedReq() {
    SUBFOLDER=$1
    if [ -f "${SUBFOLDER}/git-update" ]; then
	echo -e "\033[1;36mUpdating nested requirements\033[0m"
	cd ${SUBFOLDER}
	. git-update
	cd ${SCRIPT_DIR}
    fi
}

for ((i = 0; i < ${#SUBFOLDERS[@]}; i+=3))
do
    SUBFOLDER="${SUBFOLDERS[$i]}"
    SUBFOLDER_URL="${SUBFOLDERS[$i+1]}"
    SUBFOLDER_BRANCH="${SUBFOLDERS[$i+2]}"
    if [ -n "${SUBFOLDER}" ]  && [ -n "${SUBFOLDER_URL}" ]; then
	if [ -d "${SUBFOLDER}" ] && [ -d "${SUBFOLDER}/.git" ]; then
	    echo -e "updating existing subfolder: \033[1;32m${SUBFOLDER}\033[0m"
	    git --git-dir=${SUBFOLDER}/.git --work-tree=${SUBFOLDER} pull
	    UpdateNestedReq ${SUBFOLDER}
	else
	    echo -e "adding new subfolder: \033[1;32m${SUBFOLDER}\033[0m from \033[1;33m${SUBFOLDER_URL}\033[0m"
	    git clone -b ${SUBFOLDER_BRANCH} ${SUBFOLDER_URL} ${SUBFOLDER}
	    UpdateNestedReq ${SUBFOLDER}
	fi
    fi
done

